language: php

php:
    - 7.3
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo "session.gc_probability = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update
    - composer --version
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then php php-cs-fixer.phar --version; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar; fi

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source --no-interaction $COMPOSER_FLAGS

script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then php php-cs-fixer.phar fix --dry-run -v; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then bin/phpunit --coverage-clover build/logs/clover.xml; else bin/phpunit; fi

after_script:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.4" ]]; then php php-coveralls.phar -v; fi;
